# [START memorystore_app_yaml]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# update with Redis instance host IP, port
env_variables:
  REDISHOST:  localhost
  REDISPORT: 6379

# update with Redis instance network name
network:
  name: default

#[END memorystore_app_yaml]